services:
  ml-lab:
    build:
      context: ./
      args:
        - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    image: ml-lab:latest
    volumes:
      - type: bind
        source: ./${PROJECT_NAME}
        target: /workspace/${PROJECT_NAME}
      - type: bind
        source: ./data
        target: /workspace/data
    ports:
      - "8000:8888"

    ipc: host
    ulimits:
      stack: '67108864'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
