services:
  pytorch:
    image: nvcr.io/nvidia/pytorch:23.07-py3
    volumes:
      - type: bind
        source: ./${PROJECT}
        target: /workspace/${PROJECT}
      - type: bind
        source: ./data
        target: /workspace/data
    ports:
      - "8000:8888"
    entrypoint:
      [
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--no-browser",
        "--allow-root",
        "--LabApp.token=${TOKEN}"
      ]

    ipc: host
    ulimits:
      stack: '67108864'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
